apiVersion: apps/v1
kind: Deployment
metadata:
  name: stories-gpt-rag
  labels:
    app: stories-gpt-rag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stories-gpt-rag
  template:
    metadata:
      labels:
        app: stories-gpt-rag
    spec:
      containers:
        - name: stories-gpt-rag
          image: 490332585872.dkr.ecr.us-east-1.amazonaws.com/stories-gpt-rag
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - secretRef:
              name: openai-api-secret
